---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    author: Ram
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    name: result-app

